version: '2'

services:

#  rproxy :
#   image: eforce21/letsencrypt-nginx-proxy:1.0.2
#   ports:
#     - "80:80"
#     - "443:443"
#   volumes:
#     - "/var/run/docker.sock:/tmp/docker.sock:ro"
#   environment:
#    - LETSENCRYPT_EMAIL=m.maatkamp@gmail.com
#    - LETSENCRYPT_HOST=duval.servequake.com
#   restart: always  

#  proxy:
#   image: jwilder/nginx-proxy
#   restart: always
#   volumes:
#    - /var/local/proxy-confs:/etc/nginx/vhost.d:ro
#    - /var/run/docker.sock:/tmp/docker.sock:ro
#    - ./volumes/nginx/certs:/etc/nginx/certs
#    - ./volumes/nginx/htpasswd:/etc/nginx/htpasswd
#    - /etc/letsencrypt:/etc/letsencrypt
#   ports:
#    - 80:80
#    - 443:443

# ldap:
#  image: osixia/openldap
#  expose:
#   - "389"
#   - "636"
#  volumes:
#   - ./volumes/openldap:/var/lib/ldap
#  environment:
#   - LDAP_DOMAIN=example.com
#   - LDAP_ORGANIZATION="Example Ltd."
#   - LDAP_ROOTPASS=toor

# webldap:
#  image: osixia/phpldapadmin:0.6.9
#  expose:
#    - 80
#  # ports:
#  #   - 443:443
#  environment:
#   - PHPLDAPADMIN_LDAP_HOSTS=ldap
#   - PHPLDAPADMIN_HTTPS=false 
#   - VIRTUAL_HOST=duval.servequake.com
#   - VIRTUAL_PROTO=https
#  links:
#   - ldap
#   - rproxy

 rabbitmq: 
  image: marcelmaatkamp/rabbitmq-mqtt-ldap
  restart: always
  ports:
   - 5672:5672
   - 15672:15672
  environment:
   - VIRTUAL_HOST=duval.servequake.com
   - VIRTUAL_PORT=15672
 
 mongodb:
  image:  tutum/mongodb
  restart: always
  volumes:
   - "./volumes/mongodb/database:/data/db"
   - "./volumes/mongodb/config:/data/configdb"
   
 fabuleus_dns:
  # image: marcelmaatkamp/nodejs-dns
  build: docker-nodejs-dns
  restart: always
  ports:
   - "53:53"
  links:
   - rabbitmq:rabbitmq
  environment:
   - AMQP_URL=amqp://guest:guest@rabbitmq
   - DNS_PORT=53 

 fabuleus_dns_mongodb:
  # image: marcelmaatkamp/nodejs-dns-mongodb:latest
  build: docker-nodejs-dns-mongodb/
  restart: always
  image: marcelmaatkamp/nodejs-dns-mongodb:latest
  links:
   - rabbitmq:rabbitmq
   - mongodb:mongodb
   - fabuleus_dns:fabuleus_dns
  environment:
   - AMQP_URL=amqp://guest:guest@rabbitmq
   - MONGODB_URL=mongodb://mongodb:27017/dns 

 fabuleus_dns_mongodb_viewer:
  image: marcelmaatkamp/nodejs-dns-mongodb-viewer
  restart: always
  ports:
   - 1337:1337
  links:
   - mongodb:mongodb
   - fabuleus_dns_mongodb:fabuleus_dns_mongodb
  environment:
   - MONGODB_URL=mongodb://mongodb:27017/dns 
